kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "iqserver.fullname" . }}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.iq.storageCapacity }}
