apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.name | quote }}
  name: {{ .Values.name | quote }}
spec:
  port:
    targetPort: 8081-tcp
  to:
    kind: Service
    name: {{ .Values.name | quote }}
    weight: 100
