apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name | quote }}
  name: {{ .Values.name | quote }}
spec:
  ports:
  - name: 8081-tcp
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    deploymentconfig: {{ .Values.name | quote }}
  sessionAffinity: None
  type: ClusterIP
